from .doi import DOI
from .generic_identifier import GenericIdentifier
from .handle import HANDLE
from .identifiers_dot_org_id import IdentifiersDotOrgID
from .isbn import ISBN
from .isni import ISNI
from .issn import ISSN
from .lei import LEI
from .orcid import ORCID
from .rorid import RORID
from .rrid import RRID
from .stock_number import StockNumber
from .swhid import SWHID
