from .accessibility import Accessibility
from .comment import Comment
from .dependency import Dependency
from .funding import Funding
from .geo_coordinates import GeoCoordinates
from .location import Location
from .membership import Membership
from .quantitative_value import QuantitativeValue
from .quantitative_value_array import QuantitativeValueArray
from .quantitative_value_range import QuantitativeValueRange
from .research_product_group import ResearchProductGroup
from .web_resource import WebResource
