


class Query:

    def __init__(self, node_type, label, space, items=None):
        self.node_type = node_type
        self.label = label
        self.space = space
        self.items = [
            QueryItem("@id", filter=Filter("EQUALS", parameter="id")),
            QueryItem("https://core.kg.ebrains.eu/vocab/meta/space",
                      name="query:space",
                      filter=Filter("EQUALS", value=self.space))
        ]
        if items:
            self.items.extend(items)

    def add_item(self, item):
        assert isinstance(item, QueryItem)
        self.children.append(item)

    def serialize(self):
        query = {
            "@context": {
                "@vocab": "https://core.kg.ebrains.eu/vocab/query/",
                "query": "https://schema.hbp.eu/myQuery/",
                "propertyName": {
                    "@id": "propertyName",
                    "@type": "@id"
                },
                "merge": {
                    "@type": "@id",
                    "@id": "merge"
                },
                "path": {
                    "@id": "path",
                    "@type": "@id"
                }
            },
            "meta": {
                "type": self.node_type,
                "name": self.label,
                "description": "Automatically generated by fairgraph"
            },
            "structure": [item.serialize() for item in self.items]
        }
        return query

# todo: I think only one item can have "sort": True - need to check this


class QueryItem:

    def __init__(self, path, name=None, filter=None,
                 sorted=False, required=False, ensure_order=False,
                 children=None):
        self.path = path
        self.name = name
        self.filter = filter
        self.sorted = sorted
        self.required = required
        self.ensure_order = ensure_order
        self.children = children or []

    def add_child(self, child):
        assert isinstance(child, QueryItem)
        self.children.append(child)

    def serialize(self):
        data = {
            "path": self.path,
        }
        if self.name:
            data["propertyName"] = self.name
        if self.filter:
            data["filter"] = self.filter.serialize()
        if self.sorted:
            data["sort"] = True
        if self.required:
            data["required"] = True
        if self.ensure_order:
            data["ensureOrder"] = True
        if self.children:
            data["structure"] = [
                child.serialize() for child in self.children
            ]
        return data


class Filter:

    def __init__(self, operation, parameter=None, value=None):
        self.operation = operation
        self.parameter = parameter
        self.value = value

    def serialize(self):
        data = {
            "op": self.operation
        }
        if self.parameter:
            data["parameter"] = self.parameter
        if self.value:
            data["value"] = self.value
        return data