from datetime import datetime
try:
    from .minds import *
except ModuleNotFoundError:
    from minds import *
    
#################################################################################################
##### The following code is generated by the script in queries/code_generation_from_KGE_queries
#################################################################################################
class Abstractionlevel(MINDSObject):
    """
    docstring
    """
    _path = "/options/abstractionlevel/v1.0.0"
    type = ["uniminds:Abstractionlevel"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("abstraction_level", KGObject, "https://schema.hbp.eu/uniminds/abstractionLevel", required=False))
    


class AgeCategory(MINDSObject):
    """
    docstring
    """
    _path = "/options/agecategory/v1.0.0"
    type = ["uniminds:AgeCategory"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("age_category", KGObject, "https://schema.hbp.eu/uniminds/ageCategory", required=False))
    


class BrainStructure(MINDSObject):
    """
    docstring
    """
    _path = "/options/brainstructure/v1.0.0"
    type = ["uniminds:BrainStructure"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("brain_structure", KGObject, "https://schema.hbp.eu/uniminds/brainStructure", required=False))
    


class CellularTarget(MINDSObject):
    """
    docstring
    """
    _path = "/options/cellulartarget/v1.0.0"
    type = ["uniminds:CellularTarget"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("cellular_target", KGObject, "https://schema.hbp.eu/uniminds/cellularTarget", required=False))
    


class Country(MINDSObject):
    """
    docstring
    """
    _path = "/options/country/v1.0.0"
    type = ["uniminds:Country"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("country_of_origin", basestring, "https://schema.hbp.eu/uniminds/countryOfOrigin", required=False))
    


class Dataset(MINDSObject):
    """
    docstring
    """
    _path = "/core/dataset/v1.0.0"
    type = ["uniminds:Dataset"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("description", basestring, "http://schema.org/description", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("intended_release_date", datetime, "https://schema.hbp.eu/uniminds/intendedReleaseDate", required=False),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("brain_structure", KGObject, "https://schema.hbp.eu/uniminds/brainStructure", required=False),
      Field("cellular_target", KGObject, "https://schema.hbp.eu/uniminds/cellularTarget", required=False),
      Field("contributor", basestring, "https://schema.hbp.eu/uniminds/contributor", required=False),
      Field("created_as", basestring, "https://schema.hbp.eu/uniminds/createdAs", required=False),
      Field("custodian", KGObject, "https://schema.hbp.eu/uniminds/custodian", required=False),
      Field("doi", KGObject, "https://schema.hbp.eu/uniminds/doi", required=False),
      Field("embargo_status", KGObject, "https://schema.hbp.eu/uniminds/embargoStatus", required=False),
      Field("ethics_approval", KGObject, "https://schema.hbp.eu/uniminds/ethicsApproval", required=False),
      Field("funding_information", KGObject, "https://schema.hbp.eu/uniminds/fundingInformation", required=False),
      Field("hbp_component", KGObject, "https://schema.hbp.eu/uniminds/hbpComponent", required=False),
      Field("license", KGObject, "https://schema.hbp.eu/uniminds/license", required=False),
      Field("main_contact", basestring, "https://schema.hbp.eu/uniminds/mainContact", required=False),
      Field("main_file_bundle", basestring, "https://schema.hbp.eu/uniminds/mainFileBundle", required=False),
      Field("method", KGObject, "https://schema.hbp.eu/uniminds/method", required=False),
      Field("project", KGObject, "https://schema.hbp.eu/uniminds/project", required=False),
      Field("publication", KGObject, "https://schema.hbp.eu/uniminds/publication", required=False),
      Field("species", KGObject, "https://schema.hbp.eu/uniminds/species", required=False),
      Field("study_target", KGObject, "https://schema.hbp.eu/uniminds/studyTarget", required=False),
      Field("subjectgroup", KGObject, "https://schema.hbp.eu/uniminds/subjectGroup", required=False))
    


class Disability(MINDSObject):
    """
    docstring
    """
    _path = "/options/disability/v1.0.0"
    type = ["uniminds:Disability"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("disability", KGObject, "https://schema.hbp.eu/uniminds/disability", required=False))
    


class Doi(MINDSObject):
    """
    docstring
    """
    _path = "/options/doi/v1.0.0"
    type = ["uniminds:Doi"]
    fields = (
      Field("citation", basestring, "https://schema.hbp.eu/uniminds/citation", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("doi", KGObject, "https://schema.hbp.eu/uniminds/doi", required=False))
    


class EmbargoStatus(MINDSObject):
    """
    docstring
    """
    _path = "/options/embargostatus/v1.0.0"
    type = ["uniminds:EmbargoStatus"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("embargo_status", KGObject, "https://schema.hbp.eu/uniminds/embargoStatus", required=False))
    


class EthicsApproval(MINDSObject):
    """
    docstring
    """
    _path = "/core/ethicsapproval/v1.0.0"
    type = ["uniminds:EthicsApproval"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("hbpethicsapproval", basestring, "https://schema.hbp.eu/uniminds/hbpEthicsApproval", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("country_of_origin", basestring, "https://schema.hbp.eu/uniminds/countryOfOrigin", required=False),
      Field("ethics_approval", KGObject, "https://schema.hbp.eu/uniminds/ethicsApproval", required=False),
      Field("ethics_authority", KGObject, "https://schema.hbp.eu/uniminds/ethicsAuthority", required=False))
    


class EthicsAuthority(MINDSObject):
    """
    docstring
    """
    _path = "/options/ethicsauthority/v1.0.0"
    type = ["uniminds:EthicsAuthority"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("ethics_authority", KGObject, "https://schema.hbp.eu/uniminds/ethicsAuthority", required=False))
    


class ExperimentalPreparation(MINDSObject):
    """
    docstring
    """
    _path = "/options/experimentalpreparation/v1.0.0"
    type = ["uniminds:ExperimentalPreparation"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("experimental_preparation", KGObject, "https://schema.hbp.eu/uniminds/experimentalPreparation", required=False))
    


class File(MINDSObject):
    """
    docstring
    """
    _path = "/core/file/v1.0.0"
    type = ["uniminds:File"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("description", basestring, "http://schema.org/description", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("url", basestring, "http://schema.org/url", required=False),
      Field("brain_structure", KGObject, "https://schema.hbp.eu/uniminds/brainStructure", required=False),
      Field("file", KGObject, "https://schema.hbp.eu/uniminds/file", required=False),
      Field("method", KGObject, "https://schema.hbp.eu/uniminds/method", required=False),
      Field("mime_type", KGObject, "https://schema.hbp.eu/uniminds/mimeType", required=False),
      Field("study_target", KGObject, "https://schema.hbp.eu/uniminds/studyTarget", required=False),
      Field("subject", KGObject, "https://schema.hbp.eu/uniminds/subject", required=False),
      Field("subjectgroup", KGObject, "https://schema.hbp.eu/uniminds/subjectGroup", required=False))
    


class FileAssociation(MINDSObject):
    """
    docstring
    """
    _path = "/core/fileassociation/v1.0.0"
    type = ["uniminds:FileAssociation"]
    fields = (
      Field("from", basestring, "https://schema.hbp.eu/linkinginstance/from", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("to", basestring, "https://schema.hbp.eu/linkinginstance/to", required=False))
    


class FileBundle(MINDSObject):
    """
    docstring
    """
    _path = "/core/filebundle/v1.0.0"
    type = ["uniminds:FileBundle"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("description", basestring, "http://schema.org/description", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("url", basestring, "http://schema.org/url", required=False),
      Field("usage_notes", basestring, "https://schema.hbp.eu/uniminds/usageNotes", required=False),
      Field("brain_structure", KGObject, "https://schema.hbp.eu/uniminds/brainStructure", required=False),
      Field("cellular_target", KGObject, "https://schema.hbp.eu/uniminds/cellularTarget", required=False),
      Field("file", KGObject, "https://schema.hbp.eu/uniminds/file", required=False),
      Field("file_bundle", KGObject, "https://schema.hbp.eu/uniminds/fileBundle", required=False),
      Field("main_file_bundle", basestring, "https://schema.hbp.eu/uniminds/mainFileBundle", required=False),
      Field("method", KGObject, "https://schema.hbp.eu/uniminds/method", required=False),
      Field("mime_type", KGObject, "https://schema.hbp.eu/uniminds/mimeType", required=False),
      Field("model_instance", KGObject, "https://schema.hbp.eu/uniminds/modelInstance", required=False),
      Field("publication", KGObject, "https://schema.hbp.eu/uniminds/publication", required=False),
      Field("study_target", KGObject, "https://schema.hbp.eu/uniminds/studyTarget", required=False),
      Field("subject", KGObject, "https://schema.hbp.eu/uniminds/subject", required=False),
      Field("subjectgroup", KGObject, "https://schema.hbp.eu/uniminds/subjectGroup", required=False))
    


class FileBundleGroup(MINDSObject):
    """
    docstring
    """
    _path = "/options/filebundlegroup/v1.0.0"
    type = ["uniminds:FileBundleGroup"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True))
    


class FundingInformation(MINDSObject):
    """
    docstring
    """
    _path = "/core/fundinginformation/v1.0.0"
    type = ["uniminds:FundingInformation"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("grant_id", basestring, "https://schema.hbp.eu/uniminds/grantId", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("funding_information", KGObject, "https://schema.hbp.eu/uniminds/fundingInformation", required=False))
    


class Genotype(MINDSObject):
    """
    docstring
    """
    _path = "/options/genotype/v1.0.0"
    type = ["uniminds:Genotype"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("genotype", KGObject, "https://schema.hbp.eu/uniminds/genotype", required=False))
    


class Handedness(MINDSObject):
    """
    docstring
    """
    _path = "/options/handedness/v1.0.0"
    type = ["uniminds:Handedness"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("handedness", KGObject, "https://schema.hbp.eu/uniminds/handedness", required=False))
    


class HbpComponent(MINDSObject):
    """
    docstring
    """
    _path = "/core/hbpcomponent/v1.0.0"
    type = ["uniminds:HbpComponent"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("associated_task", basestring, "https://schema.hbp.eu/uniminds/associatedTask", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("component_owner", basestring, "https://schema.hbp.eu/uniminds/componentOwner", required=False),
      Field("hbp_component", KGObject, "https://schema.hbp.eu/uniminds/hbpComponent", required=False))
    


class License(MINDSObject):
    """
    docstring
    """
    _path = "/options/license/v1.0.0"
    type = ["uniminds:License"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("fullname", basestring, "https://schema.hbp.eu/uniminds/fullName", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("url", basestring, "http://schema.org/url", required=False),
      Field("license", KGObject, "https://schema.hbp.eu/uniminds/license", required=False))
    


class Method(MINDSObject):
    """
    docstring
    """
    _path = "/core/method/v1.0.0"
    type = ["uniminds:Method"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("description", basestring, "http://schema.org/description", required=False),
      Field("fullname", basestring, "https://schema.hbp.eu/uniminds/fullName", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("brain_structure", KGObject, "https://schema.hbp.eu/uniminds/brainStructure", required=False),
      Field("ethics_approval", KGObject, "https://schema.hbp.eu/uniminds/ethicsApproval", required=False),
      Field("experimental_preparation", KGObject, "https://schema.hbp.eu/uniminds/experimentalPreparation", required=False),
      Field("method", KGObject, "https://schema.hbp.eu/uniminds/method", required=False),
      Field("method_category", KGObject, "https://schema.hbp.eu/uniminds/methodCategory", required=False),
      Field("publication", KGObject, "https://schema.hbp.eu/uniminds/publication", required=False),
      Field("study_target", KGObject, "https://schema.hbp.eu/uniminds/studyTarget", required=False),
      Field("submethod", basestring, "https://schema.hbp.eu/uniminds/subMethod", required=False))
    


class MethodCategory(MINDSObject):
    """
    docstring
    """
    _path = "/options/methodcategory/v1.0.0"
    type = ["uniminds:MethodCategory"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("method_category", KGObject, "https://schema.hbp.eu/uniminds/methodCategory", required=False))
    


class MimeType(MINDSObject):
    """
    docstring
    """
    _path = "/options/mimetype/v1.0.0"
    type = ["uniminds:MimeType"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("mime_type", KGObject, "https://schema.hbp.eu/uniminds/mimeType", required=False))
    


class ModelFormat(MINDSObject):
    """
    docstring
    """
    _path = "/options/modelformat/v1.0.0"
    type = ["uniminds:ModelFormat"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("modelformat", KGObject, "https://schema.hbp.eu/uniminds/modelFormat", required=False))
    


class ModelInstance(MINDSObject):
    """
    docstring
    """
    _path = "/core/modelinstance/v1.0.0"
    type = ["uniminds:ModelInstance"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("description", basestring, "http://schema.org/description", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("license", KGObject, "http://schema.org/license", required=False),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("version", basestring, "http://schema.org/version", required=False),
      Field("abstraction_level", KGObject, "https://schema.hbp.eu/uniminds/abstractionLevel", required=False),
      Field("brain_structure", KGObject, "https://schema.hbp.eu/uniminds/brainStructure", required=False),
      Field("cellular_target", KGObject, "https://schema.hbp.eu/uniminds/cellularTarget", required=False),
      Field("contributor", basestring, "https://schema.hbp.eu/uniminds/contributor", required=False),
      Field("custodian", KGObject, "https://schema.hbp.eu/uniminds/custodian", required=False),
      Field("main_contact", basestring, "https://schema.hbp.eu/uniminds/mainContact", required=False),
      Field("modelformat", KGObject, "https://schema.hbp.eu/uniminds/modelFormat", required=False),
      Field("model_instance", KGObject, "https://schema.hbp.eu/uniminds/modelInstance", required=False),
      Field("modelscope", KGObject, "https://schema.hbp.eu/uniminds/modelScope", required=False),
      Field("publication", KGObject, "https://schema.hbp.eu/uniminds/publication", required=False),
      Field("study_target", KGObject, "https://schema.hbp.eu/uniminds/studyTarget", required=False))
    


class ModelScope(MINDSObject):
    """
    docstring
    """
    _path = "/options/modelscope/v1.0.0"
    type = ["uniminds:ModelScope"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("modelscope", KGObject, "https://schema.hbp.eu/uniminds/modelScope", required=False))
    


class Organization(MINDSObject):
    """
    docstring
    """
    _path = "/options/organization/v1.0.0"
    type = ["uniminds:Organization"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("created_as", basestring, "https://schema.hbp.eu/uniminds/createdAs", required=False))
    


class Person(MINDSObject):
    """
    docstring
    """
    _path = "/core/person/v1.0.0"
    type = ["uniminds:Person"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("email", basestring, "http://schema.org/email", required=False),
      Field("family_name", basestring, "http://schema.org/familyName", required=False),
      Field("given_name", basestring, "http://schema.org/givenName", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("orcid", basestring, "https://schema.hbp.eu/uniminds/orcid", required=False),
      Field("component_owner", basestring, "https://schema.hbp.eu/uniminds/componentOwner", required=False),
      Field("contributor", basestring, "https://schema.hbp.eu/uniminds/contributor", required=False),
      Field("coordinator", basestring, "https://schema.hbp.eu/uniminds/coordinator", required=False),
      Field("custodian", KGObject, "https://schema.hbp.eu/uniminds/custodian", required=False),
      Field("main_contact", basestring, "https://schema.hbp.eu/uniminds/mainContact", required=False))
    


class Project(MINDSObject):
    """
    docstring
    """
    _path = "/core/project/v1.0.0"
    type = ["uniminds:Project"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("description", basestring, "http://schema.org/description", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("coordinator", basestring, "https://schema.hbp.eu/uniminds/coordinator", required=False),
      Field("project", KGObject, "https://schema.hbp.eu/uniminds/project", required=False))
    


class Publication(MINDSObject):
    """
    docstring
    """
    _path = "/core/publication/v1.0.0"
    type = ["uniminds:Publication"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("url", basestring, "http://schema.org/url", required=False),
      Field("brain_structure", KGObject, "https://schema.hbp.eu/uniminds/brainStructure", required=False),
      Field("project", KGObject, "https://schema.hbp.eu/uniminds/project", required=False),
      Field("publication", KGObject, "https://schema.hbp.eu/uniminds/publication", required=False),
      Field("publication_id", KGObject, "https://schema.hbp.eu/uniminds/publicationId", required=False),
      Field("study_target", KGObject, "https://schema.hbp.eu/uniminds/studyTarget", required=False),
      Field("subjectgroup", KGObject, "https://schema.hbp.eu/uniminds/subjectGroup", required=False))
    


class PublicationId(MINDSObject):
    """
    docstring
    """
    _path = "/options/publicationid/v1.0.0"
    type = ["uniminds:PublicationId"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("publication", KGObject, "https://schema.hbp.eu/uniminds/publication", required=False),
      Field("publication_id", KGObject, "https://schema.hbp.eu/uniminds/publicationId", required=False),
      Field("publication_id_type", KGObject, "https://schema.hbp.eu/uniminds/publicationIdType", required=False))
    


class PublicationIdType(MINDSObject):
    """
    docstring
    """
    _path = "/options/publicationidtype/v1.0.0"
    type = ["uniminds:PublicationIdType"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("publication_id_type", KGObject, "https://schema.hbp.eu/uniminds/publicationIdType", required=False))
    


class Sex(MINDSObject):
    """
    docstring
    """
    _path = "/options/sex/v1.0.0"
    type = ["uniminds:Sex"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("sex", KGObject, "https://schema.hbp.eu/uniminds/sex", required=False))
    


class Species(MINDSObject):
    """
    docstring
    """
    _path = "/options/species/v1.0.0"
    type = ["uniminds:Species"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("species", KGObject, "https://schema.hbp.eu/uniminds/species", required=False))
    


class Strain(MINDSObject):
    """
    docstring
    """
    _path = "/options/strain/v1.0.0"
    type = ["uniminds:Strain"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("strain", KGObject, "https://schema.hbp.eu/uniminds/strain", required=False))
    


class StudyTarget(MINDSObject):
    """
    docstring
    """
    _path = "/core/studytarget/v1.0.0"
    type = ["uniminds:StudyTarget"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("fullname", basestring, "https://schema.hbp.eu/uniminds/fullName", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("study_target", KGObject, "https://schema.hbp.eu/uniminds/studyTarget", required=False),
      Field("study_target_source", KGObject, "https://schema.hbp.eu/uniminds/studyTargetSource", required=False),
      Field("study_target_type", KGObject, "https://schema.hbp.eu/uniminds/studyTargetType", required=False))
    


class StudyTargetSource(MINDSObject):
    """
    docstring
    """
    _path = "/options/studytargetsource/v1.0.0"
    type = ["uniminds:StudyTargetSource"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True))
    


class StudyTargetType(MINDSObject):
    """
    docstring
    """
    _path = "/options/studytargettype/v1.0.0"
    type = ["uniminds:StudyTargetType"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True))
    


class Subject(MINDSObject):
    """
    docstring
    """
    _path = "/core/subject/v1.0.0"
    type = ["uniminds:Subject"]
    fields = (
      Field("age", basestring, "https://schema.hbp.eu/uniminds/age", required=False),
      Field("age_rang_max", basestring, "https://schema.hbp.eu/uniminds/ageRangeMax", required=False),
      Field("age_rang_min", basestring, "https://schema.hbp.eu/uniminds/ageRangeMin", required=False),
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("age_category", KGObject, "https://schema.hbp.eu/uniminds/ageCategory", required=False),
      Field("brain_structure", KGObject, "https://schema.hbp.eu/uniminds/brainstructure", required=False),
      Field("cellular_target", KGObject, "https://schema.hbp.eu/uniminds/cellularTarget", required=False),
      Field("disability", KGObject, "https://schema.hbp.eu/uniminds/disability", required=False),
      Field("genotype", KGObject, "https://schema.hbp.eu/uniminds/genotype", required=False),
      Field("handedness", KGObject, "https://schema.hbp.eu/uniminds/handedness", required=False),
      Field("method", KGObject, "https://schema.hbp.eu/uniminds/method", required=False),
      Field("publication", KGObject, "https://schema.hbp.eu/uniminds/publication", required=False),
      Field("sex", KGObject, "https://schema.hbp.eu/uniminds/sex", required=False),
      Field("species", KGObject, "https://schema.hbp.eu/uniminds/species", required=False),
      Field("strain", KGObject, "https://schema.hbp.eu/uniminds/strain", required=False),
      Field("study_target", KGObject, "https://schema.hbp.eu/uniminds/studyTarget", required=False),
      Field("subject", KGObject, "https://schema.hbp.eu/uniminds/subject", required=False),
      Field("subjects", list, "https://schema.hbp.eu/uniminds/subjects", required=False))
    


class SubjectGroup(MINDSObject):
    """
    docstring
    """
    _path = "/core/subjectgroup/v1.0.0"
    type = ["uniminds:SubjectGroup"]
    fields = (
      Field("age_rang_max", basestring, "https://schema.hbp.eu/uniminds/ageRangeMax", required=False),
      Field("age_rang_min", basestring, "https://schema.hbp.eu/uniminds/ageRangeMin", required=False),
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("description", basestring, "http://schema.org/description", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("num_of_subjects", basestring, "https://schema.hbp.eu/uniminds/numOfSubjects", required=False),
      Field("age_category", KGObject, "https://schema.hbp.eu/uniminds/ageCategory", required=False),
      Field("cellular_target", KGObject, "https://schema.hbp.eu/uniminds/cellularTarget", required=False),
      Field("brain_structure", KGObject, "https://schema.hbp.eu/uniminds/brainStructure", required=False),
      Field("disability", KGObject, "https://schema.hbp.eu/uniminds/disability", required=False),
      Field("genotype", KGObject, "https://schema.hbp.eu/uniminds/genotype", required=False),
      Field("handedness", KGObject, "https://schema.hbp.eu/uniminds/handedness", required=False),
      Field("method", KGObject, "https://schema.hbp.eu/uniminds/method", required=False),
      Field("publication", KGObject, "https://schema.hbp.eu/uniminds/publication", required=False),
      Field("sex", KGObject, "https://schema.hbp.eu/uniminds/sex", required=False),
      Field("species", KGObject, "https://schema.hbp.eu/uniminds/species", required=False),
      Field("strain", KGObject, "https://schema.hbp.eu/uniminds/strain", required=False),
      Field("study_target", KGObject, "https://schema.hbp.eu/uniminds/studyTarget", required=False),
      Field("subjectgroup", KGObject, "https://schema.hbp.eu/uniminds/subjectGroup", required=False),
      Field("subjects", list, "https://schema.hbp.eu/uniminds/subjects", required=False))
    


class TissueSample(MINDSObject):
    """
    docstring
    """
    _path = "/core/tissuesample/v1.0.0"
    type = ["uniminds:TissueSample"]
    fields = (
      Field("alternatives", list, "https://schema.hbp.eu/inference/alternatives", required=False),
      Field("identifier", basestring, "http://schema.org/identifier", required=True),
      Field("name", basestring, "http://schema.org/name", required=True),
      Field("subject", KGObject, "https://schema.hbp.eu/uniminds/subject", required=False))
###############################################################    
### end of script-generated code
################################################################    

def list_kg_classes():
    """List all KG classes defined in this module"""
    return [obj for name, obj in inspect.getmembers(sys.modules[__name__])
            if inspect.isclass(obj) and issubclass(obj, KGObject) and obj.__module__ == __name__]
    

class UniMINDSOption():
    pass


if __name__=='__main__':

    import os
    from fairgraph import uniminds, KGClient
    token = os.environ['HBP_token']
    client = KGClient(token)
    for cls in uniminds.list_kg_classes():
        print(cls.__name__)
        # for f in cls.fields:
        #     print('    - %s' % f.name)
